version: '3.8'

services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraper_image_container
    command: python3 -m src.scraper
    volumes:
      - ./src:/app/src
    environment:
      - MINIO_PORT=${MINIO_PORT}
    depends_on:
      - minio
    env_file:
      - src/.env
  minio:
    image: docker.io/bitnami/minio:2022
    container_name: minio_container
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    env_file:
      - src/.env 
networks:
  default:
    driver: bridge

volumes:
  minio_data:
    driver: local
