FROM python:3.9-slim
WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install python-dotenv

COPY ./src /app/src

EXPOSE 5432 9000

CMD ["python3", "-m", "src.processing"]