version: '3.8'

services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: montreal-scraper
    command: python3 -m src.scraper
    volumes:
      - ./src:/app/src
    environment:
      - MINIO_ROOT_USER=Ahmad1!
      - MINIO_ROOT_PASSWORD=Ahmad1!2
      - MINIO_DEFAULT_BUCKETS=dev-raw-scraper-new
    depends_on:
      - minio

  minio:
    image: docker.io/bitnami/minio:2022
    container_name: minio_container
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=Ahmad1!
      - MINIO_ROOT_PASSWORD=Ahmad1!2
      - MINIO_DEFAULT_BUCKETS=dev-raw-scraper-new

networks:
  default:
    driver: bridge

volumes:
  minio_data:
    driver: local
