# version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - airflow-network

  minio:
    image: bitnami/minio:2022
    container_name: minio
    env_file: 
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - airflow-network

  airflow-webserver:
    image: apache/airflow:2.7.2
    container_name: airflow_webserver
    depends_on:
      - postgres
      - minio
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: minio psycopg2-binary
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - /var/run/docker.sock:/var/run/docker.sock
      - ./entrypoint.sh:/entrypoint.sh
    networks:
      - airflow-network
    entrypoint: ["/bin/bash", "/entrypoint.sh"]


  airflow-scheduler:
    image: apache/airflow:2.7.2
    container_name: airflow_scheduler
    depends_on:
      - postgres
      - airflow-webserver
    env_file: 
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: minio psycopg2-binary
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - airflow-network
    command: airflow scheduler

volumes:
  postgres_data:
  minio_data:

networks:
  airflow-network:
    driver: bridge
